#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Core\Console\Kernel;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();

$app = new Kernel((string) ($_ENV['APP_VERSION'] ?? '1.0.0'));
$app->run();
